pagopa/pagopa-ecommerce-commons

pom.xml, src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionClosedData.java, src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionClosedEvent.java, src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionClosureData.java, src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionClosureFailedEvent.java, src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionClosed.java, src/test/java/it/pagopa/ecommerce/commons/domain/v1/TransactionTest.java, src/test/java/it/pagopa/ecommerce/commons/v1/TransactionTestUtils.java
Add Nodo close payment outcome to TransactionClosedEvent
This additional information are needed in order to save the nodo close payment response outcome on the event store so that it can be retrieved from the eventstore
=> fix: add Nodo outcome to TransactionClosedEvent

src/main/java/it/pagopa/ecommerce/commons/domain/AESMetadata.java, src/main/java/it/pagopa/ecommerce/commons/domain/Confidential.java, src/main/java/it/pagopa/ecommerce/commons/domain/ConfidentialMetadata.java, src/main/java/it/pagopa/ecommerce/commons/domain/v1/Email.java, src/main/java/it/pagopa/ecommerce/commons/utils/AESCipher.java, src/main/java/it/pagopa/ecommerce/commons/utils/ConfidentialDataManager.java, src/test/java/it/pagopa/ecommerce/commons/domain/AESMetadataTest.java, src/test/java/it/pagopa/ecommerce/commons/domain/ConfidentialTest.java
* add `Confidential<T>` class to handle sensitive data
This PR adds the `Confidential<T>` data type that can be used to handle sensitive data that should be encrypted or protected in some way.
Currently the only mechanism implemented here is encryption via AES in GCM mode with a 12 byte long IV, a 16 byte long salt and no padding.
This is achieved through collaboration of different classes:
* a class implementing the protection mechanism, currently only `AESCipher` is available
* a metadata record used for serializing metadata related to the algorithm used by the implenting class (currently only `AESMetadata` is available)
* a `Mode` enumeration value used to identify the protection mechanism (currently only  `AES_GCM_NOPAD` is available)
* the class `ConfidentialDataManager` used to tie …
=> [CHK-912] feat(privacy): add `Confidential<T>` class to handle sensitive data

pom.xml, src/main/java/it/pagopa/ecommerce/commons/annotations/Warmup.java, src/main/java/it/pagopa/ecommerce/commons/annotations/WarmupMethod.java, src/main/java/it/pagopa/ecommerce/commons/utils/warmup/ControllerWarmup.java, src/main/java/it/pagopa/ecommerce/commons/utils/warmup/annotationprocessor/WarmupAnnotationProcessor.java, src/main/resources/META-INF/services/javax.annotation.processing.Processor, src/test/java/it/pagopa/ecommerce/commons/utils/warmup/ControllerWarmupTest.java, src/test/java/it/pagopa/ecommerce/commons/utils/warmup/annotationprocessor/WarmupAnnotationProcessorTest.java
Depends on: https://github.com/pagopa/pagopa-ecommerce-commons/pull/72
Add generic Controller warmup logic.
The mail class is `ControllerWarmup` that listens for `ContextRefreshedEvent`, raised by Spring framework when ApplicationContext has been started.
Starting from this event, ApplicationContext is then scanned searching for all managed beans annotated with `RestController` annotation and, for each of those, scanning all methods annotated with @WarmupMethod custom annotation.
Those annotated methods are finally executed performing the specific implemented warmup logic and logging overall and each method elapsed time
Those modifications are needed in order to have a common logic to perform module-specific warmup logic (such as performing an HTTP request on a specific endpoint to let …
=> [CHK-1393] feat: add warmup controller logic

src/main/java/it/pagopa/ecommerce/commons/documents/v1/Transaction.java, src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionEvent.java, src/main/java/it/pagopa/ecommerce/commons/domain/v1/EmptyTransaction.java, src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionId.java, src/test/java/it/pagopa/ecommerce/commons/documents/v1/TransactionDocumentTest.java, src/test/java/it/pagopa/ecommerce/commons/domain/v1/TransactionIdTests.java, src/test/java/it/pagopa/ecommerce/commons/domain/v1/TransactionTest.java, src/test/java/it/pagopa/ecommerce/commons/v1/TransactionTestUtils.java
Modified transaction id to be shorter than 35 chars. This modification has been carried out trimming `-`characters from UUID string that produce a 32 chars string (36 UUID string format less 4 dashes)
This modification is needed in order to generate a transaction id lesser that the Nodo expected 35 chars and use the same transaction id across the whole application
Jnuit tests
=> fix: transaction id must not be longer than 35 chars

src/main/java/it/pagopa/ecommerce/commons/redis/templatewrappers/RedisTemplateWrapper.java, src/test/java/it/pagopa/ecommerce/commons/redis/templatewrappers/PaymentRequestInfoRedisTemplateWrapperTest.java
Change Redis delete method from GETDEL to DEL ones.
RedisTemplate OpsForVal expose GETDEL Redis method for get and delete a key. 
This method, by the way, is supported starting from Redis 6.2.0 and ecommerce Redis version is 6.0 so this method is not supported. 
DEL method, instead, is supported starting from Redis 1.0 version.
Junit test and local tests
=> fix: redis delete

src/main/java/it/pagopa/ecommerce/commons/repositories/PaymentRequestInfo.java, src/test/java/it/pagopa/ecommerce/commons/v1/TransactionTestUtils.java
Add activation date into PaymentRequstInfo redis cache entity.
The activation date will be set when the transaction is first created and will be used to monitor subsequent activations against the payment token validity time left
Those modifications are needed in order to monitor subsequent transactions activations payment token validity time left
Junit tests
=> feat: add transaction activation date into cache

src/main/java/it/pagopa/ecommerce/commons/documents/BaseTransactionEvent.java, src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionEvent.java
* fix Spring annotation in inherited `BaseTransactions` fiels
This PR fixes a runtime loading issue of event classes. In particular Spring cannot disambiguate between base class and child class when applying annotation to fields with the same name.
This fix moves the annotations to the base class.
=> fix(events): fix Spring annotation in inherited `BaseTransaction`'s fields

src/main/java/it/pagopa/ecommerce/commons/domain/v1/RptId.java
Update the rpt id regex according to the document definition [numero avviso](https://pagopa.atlassian.net/wiki/spaces/PAG/pages/132808762/Numero+Avviso) e [pa cf](https://www.agenziaentrate.gov.it/portale/web/guest/schede/istanze/codice-fiscale-modello-aa5_6/scheda-info-cf-aa5_6-enti-e-pa). The first document asserts that the notice number is composed by 18 digits. The second(from Agenzia delle Entrate) asserts that the fiscal code is composed by 11 digits. So the rptId is composed exactly by 29 digits
Change the RptId regex
Using standard regex for rptId definition
=> fix(rptId): fix rptid regex

clients/api-specs/npg.yaml, src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java, src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Add the npg cancel payment client implementation
This feature is fully  backwards-compatible, since it is only a method adding
- Add the npg client refund payment invocation (https://developer.nexi.it/it/api/post-build-cancel)
- Add test for new method of npgClient
To handle refund for transactions payed via npg
Unit test ran
=> [CHK-1862] feat(refund): add refund payment method for npg client

.github/workflows/create_pr_with_version_update.yaml
Actions triggered automatically via `release` with `published` are executed in their own branch and not on `main`.
The action has been refactored to use tags and check whether the tag was applied on `main` in order to fix permission issues.
Prayers
=> refactor(auto-pr): trigger action on tag push rather than on release publishing

.github/workflows/create_pr_with_version_update.yaml
* refactor action to trigger on GH release
* use different action to get latest tag
* fix missing checkout of pagopa-ecommerce-commons to get tag
* use different paths for repos
* use GITHUB_REF instead of computing latest tag
=> fix(auto-pr): Refactor action to trigger on GitHub release rather than on tag push

src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionExpired.java, src/test/java/it/pagopa/ecommerce/commons/domain/v1/TransactionTest.java
Add state transition from `EXPIRED` back to `NOTIFICATION_REQUESTED` for v1 events
Add state transition from `EXPIRED` to `NOTIFICATION_REQUESTED` in order to make sendPaymentResult processing available also for those transaction that have been marked as expired after the 65 mins timeout
=> fix(event-reduce): add reduce logic to recover expired transaction

src/main/java/it/pagopa/ecommerce/commons/exceptions/CheckoutRedirectConfigurationException.java, src/main/java/it/pagopa/ecommerce/commons/exceptions/CheckoutRedirectConfigurationType.java, src/main/java/it/pagopa/ecommerce/commons/exceptions/CheckoutRedirectMissingPspRequestedException.java, src/main/java/it/pagopa/ecommerce/commons/utils/CheckoutRedirectPspApiKeysConfig.java, src/test/java/it/pagopa/ecommerce/commons/utils/CheckoutRedirectPspApiKeysConfigTest.java
* add CheckoutRedirectPspApiKeysConfig bean to hold Checkout Redirect PSP API keys
This PR adds an object representing Checkout Redirect PSP API keys to be used by `transactions-service` and `event-scheduler-service`
=> [CHK-2321] feat(checkout-redirect): add `CheckoutRedirectPspApiKeysConfig` bean to hold Checkout Redirect PSP API keys

src/main/java/it/pagopa/ecommerce/commons/redis/templatewrappers/RedisTemplateWrapper.java, src/main/java/it/pagopa/ecommerce/commons/utils/UniqueIdUtils.java, src/test/java/it/pagopa/ecommerce/commons/redis/v1/templatewrappers/PaymentRequestInfoRedisTemplateWrapperTest.java
Add redis template operations for:
- retrieve all keys and entries in keyspace
- write event to event stream with/without events trimming operation
- create/destroy event stream consumer group
Those modifications are needed in order to perform stream operations and retrieve all entries from redis
Junit tests + tests with eCommerce locals
=> feat(redis template): [CHK-2388] add ops for stream and for get all entries

src/main/java/it/pagopa/ecommerce/commons/client/NodeForwarderClient.java, src/test/java/it/pagopa/ecommerce/commons/client/NodeForwarderClientTest.java
Add explicit default header for Node Forwarder client setting api key as `Ocp-Apim-Subscription-Key` header
This fix is required since specs does not provide authorization header for proxy api calls making api call being sent without api key header
Junit tests
=> fix: set api key into Node Forwarder api call

src/main/java/it/pagopa/ecommerce/commons/queues/TracingUtils.java
This PR fix an issue where more than one traces are associated to same parent. This happens especially on storage queue consumer where all traces are correlated to same parent.
=> fix: [CHK-2879] Remove set parent on tracing remote span for mono

src/main/java/it/pagopa/ecommerce/commons/queues/TracingUtils.java
Reverts pagopa/pagopa-ecommerce-commons#201
=> Revert "fix: [CHK-2879] Remove set parent on tracing remote span for mono"

pom.xml, src/main/java/it/pagopa/ecommerce/commons/queues/TracingUtils.java
* use `ContextPropagationOperator` to propagate otel context
This change fixes a context propagation bug when creating new spans within a reactive chain.
This bug meant that when creating a new `Span` linked with a remote tracing context the local tracing context would be lost, leading to missing child spans.
**Before**
**After**
=> [CHK-2850] fix(tracing): use `ContextPropagationOperator` to propagate otel context

src/main/java/it/pagopa/ecommerce/commons/domain/Claims.java, src/main/java/it/pagopa/ecommerce/commons/utils/JwtTokenUtils.java, src/test/java/it/pagopa/ecommerce/commons/utils/JwtTokenUtilsTests.java
Since we introduced `userId` validation for `ecommerce-for-io` api group, we need to add the userId to the jwt token claims. This PR introduce this extension for Claims
Add userId as possible claim for jwt token
Enforce `ecommerce-for-io` api group security by checking `userId` value
=> [CHK2861] fix(jwt-token): add userId in possible claims of jwt token

clients/api-specs/npg.yaml
Add `GET orders` api trailing `/`
This modification is needed since order id can contains `.` (dots) in it's value and this cause the GET orders url to be misinterpretated by NPG.
As per NPG suggestion, adding a trailing `/` fixes this situation avoiding this kind of problem (order id is a path parameter and is present in the last URL part  
Local tests with eCommerce local
=> fix(npg-client): add GET orders URL trailing slash

src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionAuthorizationRequestData.java, src/main/java/it/pagopa/ecommerce/commons/domain/v2/Transaction.java, src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java, src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Add optional `idBundle` field into v2 authorization requested event
This modification is needed in order to trace GEC idBundle into authorization requested event so that this field could be propagated to the Nodo into Close payment request.
FIeld have been marked as nullable in order to be backward compatible with previously written events where this field is not written
Junit tests
=> feat: add optional idBundle field into auth requested event

src/main/java/it/pagopa/ecommerce/commons/utils/NpgClientUtils.java, src/test/java/it/pagopa/ecommerce/commons/utils/NpgClientUtilsTest.java
- Add utils class to get paymentEndToEndId from Npg getOrder
This PR centralizes the method for retrieving the paymentEndToEndId from the NPG getOrder response, enabling it to be reused across multiple services, including the event-dispatcher-service and the transaction-scheduler-service.
JUnit Test
=> [PPABV-61] Add utils class to get paymentEndToEndId from Npg getOrder
