pagopa/pagopa-ecommerce-commons

- src/main/java/it/pagopa/ecommerce/commons/documents/TransactionAuthorizationStatusUpdateData.java
- src/main/java/it/pagopa/ecommerce/commons/documents/TransactionClosureSendData.java
- src/test/java/it/pagopa/ecommerce/commons/TransactionUtils.java
> [CHK-742] refactor(transaction-events): move `authorizationCode` field from closure event to auth status update event

- pom.xml
- src/main/java/it/pagopa/ecommerce/commons/documents/Transaction.java
- src/main/java/it/pagopa/ecommerce/commons/documents/TransactionAddReceiptData.java
- src/main/java/it/pagopa/ecommerce/commons/documents/TransactionAuthorizationStatusUpdateData.java
- src/main/java/it/pagopa/ecommerce/commons/documents/TransactionClosureSendData.java
- src/main/java/it/pagopa/ecommerce/commons/documents/TransactionExpiredData.java
- src/main/java/it/pagopa/ecommerce/commons/documents/TransactionRefundedData.java
- src/main/java/it/pagopa/ecommerce/commons/domain/EmptyTransaction.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionActivated.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionActivationRequested.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionClosed.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionWithClosureError.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionWithCompletedAuthorization.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionWithRequestedAuthorization.java
- src/main/java/it/pagopa/ecommerce/commons/domain/pojos/BaseTransaction.java
- src/main/java/it/pagopa/ecommerce/commons/redis/RedisConfiguration.java
- src/main/java/it/pagopa/ecommerce/commons/repositories/PaymentRequestsInfoRepository.java
- src/main/java/it/pagopa/ecommerce/commons/utils/TransactionUtils.java
- src/test/java/it/pagopa/ecommerce/commons/TransactionUtils.java
- src/test/java/it/pagopa/ecommerce/commons/documents/TransactionDocumentTest.java
- src/test/java/it/pagopa/ecommerce/commons/domain/TransactionTest.java
- src/test/java/it/pagopa/ecommerce/commons/utils/TransactionUtilsTest.java
1. Changed TransactionStatusDTO generated classes package in order to avoid conflicts with the transaction module generated one
2. Removed ConditionalOnBean annotation from redis configuration
3. Add Repository annotation on PaymentRequestInfoRepository
1. This module generate classes with the same package and name as of the transactions generated ones. This causes Linkage errors importing this library into transaction module because two version of the same classes exists and cause Linkage errors since this classes are loaded by different class loaders
2. Removed this conditional annotation since no RedisTemplate instance is present into classpath causing redis configuration to not be loaded properly by the transaction module
3. Add this annotation to enable class loader to discover this …
> [CHK-864] fixes for transaction integration

- pom.xml
- src/test/java/it/pagopa/ecommerce/commons/TransactionTestUtils.java
- src/test/java/it/pagopa/ecommerce/commons/documents/TransactionDocumentTest.java
- src/test/java/it/pagopa/ecommerce/commons/domain/TransactionTest.java
This PR introduces a test jar usable in downstream projects as a dependency. Essentially it exposes test utilities.
Specifying a test dependency can be done [as noted here](https://stackoverflow.com/questions/4444799/publish-test-utils-from-maven-project)
[`TransactionUtils`](https://github.com/pagopa/pagopa-ecommerce-commons/blob/main/src/test/java/it/pagopa/ecommerce/commons/TransactionUtils.java) is a test-only class that allows quick creation of events, documents and domain objects for testing purposes.
Its usefulness can be applied to downstream projects as well in tests, given that these are common setup operations.
N/A
> build: add test jar to use tests in downstream projects

- src/main/java/it/pagopa/ecommerce/commons/documents/NoticeCode.java
- src/main/java/it/pagopa/ecommerce/commons/documents/Transaction.java
- src/main/java/it/pagopa/ecommerce/commons/documents/TransactionActivationRequestedData.java
- src/main/java/it/pagopa/ecommerce/commons/domain/EmptyTransaction.java
- src/main/java/it/pagopa/ecommerce/commons/domain/NoticeCode.java
- src/main/java/it/pagopa/ecommerce/commons/domain/PaymentContextCode.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionActivated.java
- src/main/java/it/pagopa/ecommerce/commons/domain/pojos/BaseTransactionWithPaymentToken.java
- src/test/java/it/pagopa/ecommerce/commons/TransactionTestUtils.java
> [CHK-891] add paymentContextCode to NoticeCode

- src/main/java/it/pagopa/ecommerce/commons/documents/Transaction.java
- src/main/java/it/pagopa/ecommerce/commons/documents/TransactionActivatedData.java
- src/main/java/it/pagopa/ecommerce/commons/documents/TransactionActivationRequestedData.java
- src/main/java/it/pagopa/ecommerce/commons/domain/EmptyTransaction.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionActivated.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionActivationRequested.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionClosed.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionWithClosureError.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionWithCompletedAuthorization.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionWithRequestedAuthorization.java
- src/main/java/it/pagopa/ecommerce/commons/domain/pojos/BaseTransaction.java
- src/main/java/it/pagopa/ecommerce/commons/domain/pojos/BaseTransactionWithPaymentToken.java
- src/test/java/it/pagopa/ecommerce/commons/TransactionTestUtils.java
- src/test/java/it/pagopa/ecommerce/commons/documents/TransactionDocumentTest.java
Refactored origin to clientId 
ClientId is a better name for field semantic: this field, in fact, identify the transaction originator client 
Local junit test
> feat: refactor origin to clientId

- src/main/java/it/pagopa/ecommerce/commons/repositories/PaymentRequestInfo.java
* make PA name, payment description and due date nullable in `PaymentRequestInfo`
When contacting Nodo to get informations about a notice we memorize those into a `PaymentRequestInfo` data structure. This PR removes some non-nullability constraints that cannot be upheld by Nodo APIs.
> refactor(payment-request-info): make PA name, payment description and due date nullable in `PaymentRequestInfo`

- src/main/java/it/pagopa/ecommerce/commons/domain/EmptyTransaction.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionActivated.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionActivationRequested.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionClosed.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionWithClosureError.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionWithCompletedAuthorization.java
- src/main/java/it/pagopa/ecommerce/commons/domain/TransactionWithRequestedAuthorization.java
- src/main/java/it/pagopa/ecommerce/commons/domain/pojos/BaseTransaction.java
- src/main/java/it/pagopa/ecommerce/commons/domain/pojos/BaseTransactionWithPaymentToken.java
- src/test/java/it/pagopa/ecommerce/commons/TransactionTestUtils.java
- src/test/java/it/pagopa/ecommerce/commons/domain/TransactionTest.java
* hard-code transaction status into domain classes instead of accepting a `status` parameter
Transaction domain classes had a `status` member while it didn't really make sense for them to do so. Especially considering that potentially a transaction instance could have a different status than what the name would suggest.
For example, this was possible before:
```java
TransactionClosed transactionClosed = /* ... */
transactionClosed = (TransactionClosed) transactionClosed.withStatus(TransactionStatusDto.AUTHORIZED);
assertEquals(TransactionStatusDto.AUTHORIZED, transactionClosed.getStatus());
```
Which doesn't really make sense.
> [CHK-896] refactor(transaction): hard-code transaction status into domain classes

- src/test/java/it/pagopa/ecommerce/commons/TransactionTestUtils.java
* add test utils to create closure-retry and refund-retry events
> test(utils): add test utils to create closure-retry and refund-retry events

- src/main/java/it/pagopa/ecommerce/commons/utils/TransactionUtils.java
- src/test/java/it/pagopa/ecommerce/commons/utils/TransactionUtilsTest.java
* add utility function to get transaction fee
> feat(utils): add utility function to get transaction fee

- src/test/java/it/pagopa/ecommerce/commons/TransactionTestUtils.java
* make `authorizationId` a string representation of a UUID in test utilities
This PR changes authorization id for test utility classes from a generic string to a UUID to better uniform to the expected interface of the payment gateway.
> refactor(tests-utils): make `authorizationId` a string representation of a UUID

- specs/state_machine.js
> feat(states): add eCommerce state machine definition

- specs/state_machine.js
> fix(state-machine): fix state machine definition

- src/main/java/it/pagopa/ecommerce/commons/utils/v1/TransactionUtils.java
* mark `AUTHORIZATION_COMLPETED` status as refundable
> feat(transaction): mark `AUTHORIZATION_COMLPETED` status as refundable

- specs/state_machine.js
* add transition CLOSURE_ERROR -> UNAUTHORIZED when sending KO closePayment after auth denied
> feat(spec): add transition CLOSURE_ERROR -> UNAUTHORIZED when sending KO closePayment after auth denied

- pom.xml
- specs/state_machine.js
* update state machine with refund-retry and cancellation request
This PR updates the state machine diagram with the following changes: 
* added a REFUND_ERROR state triggered by an error when trying to refund a transaction
* added an intermediate CANCELLATION_REQUESTED state to handle possible failures when invoking `closePayment` when user requests a transaction to be aborted
* added REFUND_REQUESTED intermediate state to handle failures when requesting refund
Depends on #40
> feat(state-machine): update state machine with refund-retry and cancellation request

- src/main/java/it/pagopa/ecommerce/commons/utils/v1/TransactionUtils.java
* mark `AUTHORIZATION_REQUESTED` status as refundable
> refactor(transaction): mark `AUTHORIZATION_REQUESTED` status as refundable

- src/main/java/it/pagopa/ecommerce/commons/domain/AESMetadata.java
Add persistence constructor used by Mongo data for events serialization/deserialization
This modification is needed in order to make spring-data working correctly
> fix: add default constructor for mongo

- src/main/java/it/pagopa/ecommerce/commons/repositories/PaymentRequestInfo.java
- all fields of `PaymentRequestInfo` except `id` as nullable;
- delete old (and useless 😁) field `isNM3`.
> feat: make all fields inside `PaymentRequestInfo` nullable except for `rptId`

- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionWithClosureError.java
Make transactionAtPreviousState method public so that can be used outside
This method can be used by caller modules to obtain an Either mapping the output statuses
Local junit test
> fix: make transactionAtPreviousState public to be used from scheduler

- src/test/java/it/pagopa/ecommerce/commons/v1/TransactionTestUtils.java
Add utility method for perform events reduction and obtain corresponding BaseTransaction
This method can be reused into tests for create BaseTransaction from an events stream
Local test
> feat: add utility method for events reduction

- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionAuthorizationCompleted.java
- src/test/java/it/pagopa/ecommerce/commons/domain/v1/TransactionTest.java
Add transition from auth completed to refund requested 
This modification is needed in order to reflect state transition from `AUTHORIZATION_COMPLETED` -> `REFUND_REQUESTED`
Local junit test
> fix:add transition from auth completed to refund requested

- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionRefunded.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionWithRefundError.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/pojos/BaseTransactionRefunded.java
- src/test/java/it/pagopa/ecommerce/commons/v1/TransactionTestUtils.java
Make transaction with refund error extends transaction with refund requested
This modification is needed in order to have the correct aggregate hierarchy
> fix: transaction refund error hierarchy

- specs/state_machine.js
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionAuthorizationCompleted.java
- src/test/java/it/pagopa/ecommerce/commons/domain/v1/TransactionTest.java
Remove invalid state transition `AUTHORIZATION_COMPLETED` --> `REFUND_REQUESTED` from aggregate and state machine script
This modification remove the above invalid state transition
Junit test
> fix: remove invalid transition from auth completed to refund requested

- specs/state_machine.js
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionWithUserReceiptKo.java
- src/test/java/it/pagopa/ecommerce/commons/domain/v1/TransactionTest.java
add NOTIFIED_KO --> EXPIRED transition
add NOTIFIED_KO --> EXPIRED transition
> feat: add NOTIFIED_KO --> EXPIRED transition

- specs/state_machine.js
Add state `NOTIFICATION_ERROR`.
This state is used to signal that an error occurred sending mail recepit to the user after sendPaymentResult outcome received.
From this state the transaction can recover and go to NOTIFIED_OK/KO based on the sendPaymentResult outcome or goes to REFUND_REQUESTED state in case no more attempts are left for attempting a retry.
Finally transaction can go to EXPIRED state in case the transaction is stuck into NOTIFICATION_ERROR state.
Two new events have been created contextually to the new state:
- `ADD_USER_RECEIPT_ERROR`: event that will make transaction step from CLOSED to NOTIFICATION_ERROR state
- `ADD_USER_RECEIPT_RETRY`: event that will be fired for perform notification process retry
This new state and events are needed to cover retry on send user …
> feat: add notification error state with retry mechanism

- specs/state_machine.js
Remove illegal state transition from NOTIFICATION_REQUESTED to REFUND_REQUESTED state
Remove illegal state transition from NOTIFICATION_REQUESTED to REFUND_REQUESTED state
> fix: remove illegal transition from NOTIFICATION_REQUESTED

- src/main/java/it/pagopa/ecommerce/commons/utils/v1/TransactionUtils.java
- src/test/java/it/pagopa/ecommerce/commons/utils/v1/TransactionUtilsTest.java
Removed `REFUND_REQUESTED` and `REFUND_ERROR` from transient statuses list
This modification is needed because `REFUND_REQUESTED` and `REFUND_ERROR` are not transient statuses and expiration has not to be evaluated for those statuses by expiration queue
Junit tests
> fix: removed REFUND_REQUESTED and REFUND_ERROR from transient statuses

- src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionAuthorizationCompletedData.java
- src/main/java/it/pagopa/ecommerce/commons/utils/EuroUtils.java
- src/test/java/it/pagopa/ecommerce/commons/utils/v1/EuroUtilsTest.java
- src/test/java/it/pagopa/ecommerce/commons/v1/TransactionTestUtils.java
Added the PGS completion timestamp to the authorization completion event.
The change was made to correctly value in closePayment asynchronously the PGS authorization completion timestamp value.
> CHK-1476-added-timestamp-into-completed-event

- src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionUserReceiptData.java
Set receivingOfficeName nullable in transactionUserReceiptData
Set receivingOfficeName nullable in transactionUserReceiptData
Set receivingOfficeName nullable in transactionUserReceiptData since it could be null from nodo
> [CHK-1515] receivingOfficeName nullable

- src/main/java/it/pagopa/ecommerce/commons/documents/v1/Transaction.java
Update View with additional info according to [RFC](https://pagopa.atlassian.net/wiki/spaces/I/pages/703857491/Mapping+stato+transazione+-+pagina+di+esito)
- Add paymentGatewayId
- Add authorizationCode/authorizationError
- Add sendPaymentResult outcome (OK/KO)
- Add additional info for correctly handle "pagina esito" landing page
> [CHK-1533] feat: add outcome info for transaction view

- src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionAuthorizationCompletedData.java
- src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionAuthorizationRequestData.java
- src/test/java/it/pagopa/ecommerce/commons/v1/TransactionTestUtils.java
- Added errorcode field within the **TransactionAuthorizationCompletedEvent**.
- Added brand field within the **TransactionAuthorizationRequestedEvent**.
The change was made to save the **brand** of the card used during payment and the possible **errorCode** received by PGS during authorization.
The tests were performed locally with ecommerce-local.
> CHK-1531-save-brand-and-pgs-errorCode

- src/main/java/it/pagopa/ecommerce/commons/documents/v1/Transaction.java
> feat(view): update view name

- pom.xml
- src/main/java/it/pagopa/ecommerce/commons/documents/v1/PaymentNotice.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/EmptyTransaction.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/PaymentNotice.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionActivated.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/pojos/BaseTransactionWithPaymentToken.java
- src/main/java/it/pagopa/ecommerce/commons/repositories/PaymentRequestInfo.java
- src/test/java/it/pagopa/ecommerce/commons/v1/TransactionTestUtils.java
Add isAllCCP flag to handle GEC calculate fee api update
Add the flag to
- PaymentNotice
- PaymentRequestInfo
- TransactionActivated
Add test
> [CHK-1612] All ccp in payment request

- src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionUserReceiptData.java
Add sendPaymentResult NOT_RECEIVED enumeration value to be used once a close payment with response outcome is received to signal that the transaction has not received yet the sendPaymentResult
This modification is needed on order to mark all transactions that has not received yet the sendPaymentResult
Junit tests
> feat(domain): add send payment result NOT_RECEIVED notification

- src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionAuthorizationRequestData.java
- src/test/java/it/pagopa/ecommerce/commons/v1/TransactionTestUtils.java
Add flag on transaction auth data to handle psp on us info
> [CHK-1680] add pspOnUs flag

- src/main/java/it/pagopa/ecommerce/commons/documents/BaseTransactionEvent.java
- src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionEvent.java
- src/test/java/it/pagopa/ecommerce/commons/documents/v1/TransactionDocumentTest.java
* add `BaseTransactionEvent` as perennial base structure for eCommerce events
This PR adds an unversioned `BaseTransactionEvent` class.
This class is meant as a base structure for events regardless of version, meaning that
**events should extend this base structure in every present and future version**.
> refactor(events): add `BaseTransactionEvent` as perennial base structure for eCommerce events

- .github/actions/check-pr-semver-labels/action.yml
- .github/workflows/check_pr.yml
- .github/workflows/deploy.yml
- README.md
Add github action that check for the presence of well-formed tags that will be used to trigger semantic versioning parameters for deploy module once PR is merge on main branch.
Those tags are:
| Tag                | Semantic versioning scope | Meaning                                                           |
|--------------------|---------------------------|-------------------------------------------------------------------|
| patch              | Application version       | Patch-bump application version into pom.xml and Chart app version |
| minor              | Application version       | Minor-bump application version into pom.xml and Chart app version |
| major              | Application version       | Major-bump application version into pom.xml and Chart app version |
| …
> feat(CD): deploy on PR merge

- .github/actions/check-pr-semver-labels/action.yml
Fix pr number extraction
Fix pr number extraction
> fix: pr extraction number from commit message

- src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionAuthorizationRequestData.java
- src/test/java/it/pagopa/ecommerce/commons/v1/TransactionTestUtils.java
👉🏻 Added field paymentMethodDescription into AuthorizationRequestData. 🚀
The change was made to allow the payment method description to be saved during the authorization phase. 👀
> feat(paymentMethodDescription) added payment method description into AuhorizationRequestEvent

- .github/workflows/deploy.yml
> Fix deploy pipeline trigger

- .github/workflows/deploy.yml
Fix deploy pipeline trigger condition
Fix deploy pipeline trigger condition
> fix(deploy-action): fix pipeline trigger

- src/main/java/it/pagopa/ecommerce/commons/domain/v1/Email.java
- src/test/java/it/pagopa/ecommerce/commons/domain/v1/EmailTest.java
Make mail validation case insensitive
Make mail validation case insensitive
Junit tests
> fix(mail-validation): make validation case insensitive

- src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionEvent.java
- src/test/java/it/pagopa/ecommerce/commons/documents/v1/serialization/TransactionEventTypeResolverTest.java
* mark `eventCode` field as `visible` for type identification
This fixes a deserialization bug where `eventCode` would be mapped to `null` during deserialization
> fix(events): mark `eventCode` field as `visible` for type identification

- src/main/java/it/pagopa/ecommerce/commons/queues/TracingUtils.java
> fix(tracing): don't create a `Scope` when tracing `Mono`s

- src/main/java/it/pagopa/ecommerce/commons/domain/v1/pojos/BaseTransactionWithRefundRequested.java
- src/test/java/it/pagopa/ecommerce/commons/domain/v1/TransactionTest.java
Add transaction at previous step for `BaseTransactionWithRefundRequested` aggregate
This modification is needed in order to retrieve transaction before refund has been requested
Junit test
> feat: add base transaction at previous step for transaction with refund requested

- src/main/java/it/pagopa/ecommerce/commons/redis/templatewrappers/RedisTemplateWrapper.java
* unseal `RedisTemplateWrapper`
Given that `RedisTemplateWrapper` is a class that can be used for general use-cases, it can be useful to extend it outside of `pagopa-ecommerce-commons`.
> refactor(redis): unseal `RedisTemplateWrapper`

- src/main/java/it/pagopa/ecommerce/commons/redis/templatewrappers/RedisTemplateWrapper.java
* make `RedisTemplateWrapper` public
> refactor(redis): make `RedisTemplateWrapper` public

- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
- src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
* add payment method enumeration to NPG client
This change makes it possible to call `order/build` NPG API through our client with any payment method instead of cards only.
Unit tests
> [CHK-1782] refactor(npg-client): add payment method enumeration to NPG client

- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
- src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Depends on https://github.com/pagopa/pagopa-ecommerce-commons/pull/118
Added new method into NpgClient for retrieve card data from NPG.
The change was made to retrieve card data.
> feat: CHK-1824 client for retrieve card data from NPG

- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
- src/main/java/it/pagopa/ecommerce/commons/exceptions/NpgResponseException.java
- src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
* add NPG error codes enum
* add error codes returned from NPG error responses to `NpgResponseException`+
* log NPG errors into monitoring span in case of errors
This PR enhances monitoring and error logging when calling NPG.
> [CHK-1787] refactor(npg-client): refactor NPG error logging

- clients/api-specs/npg.yaml
- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
- src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Modified api path into NPG openapi.
The change was made to correct the NPG api path in the openapi
> fix(openapi): fixed npg api path into openapi

- clients/api-specs/npg.yaml
- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
- src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
- delete api key schema
- add default and psp API key given npg method
- add confirm payment method
The goal of this PR is to add the `confirmPayment` method to` npg-client`. To do this, a refactoring on the npg openapi specs was needed to distinguish the default api key from those related to psp.
> feat(npg): CHK-1833 add confirm payment for npg client

- pom.xml
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionId.java
- src/test/java/it/pagopa/ecommerce/commons/domain/v1/TransactionIdTests.java
* add conversion methods to and from base64 to `TransactionId`
Minor refactor to lift these methods from `transactions-service` because these methods are now needed in `payment-methods` too
Local unit tests
> feat(transaction-id): add conversion methods to and from base64 to `TransactionId`

- clients/api-specs/npg.yaml
Added GDI_VERIFICATION into StateEnum
> fix(NPG openapi): added new element for State enum

- src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionAuthorizationRequestData.java
Added NPG payment gataway
Added new npg payment gateway for set information into event
> fix(PaymentGateway): added new paymentGateway

- src/main/java/it/pagopa/ecommerce/commons/documents/BaseTransactionView.java
- src/main/java/it/pagopa/ecommerce/commons/documents/v1/Transaction.java
- src/main/java/it/pagopa/ecommerce/commons/documents/v2/Transaction.java
- src/main/java/it/pagopa/ecommerce/commons/utils/v1/TransactionUtils.java
- src/main/java/it/pagopa/ecommerce/commons/utils/v2/TransactionUtils.java
- Add version agnostic super class for TransactionView document in order to use this class into spring crud repositories for transaction view information retrieval
- Explicitate qualifier for TransactionUtils versioned component
Those modification are needed in order to handle transaction view multiple versions data fetch with crud repositories
Junit test + local test with eCommerce local (updating transaction-service with this eCommerce commons branch and performing read/write for transaction view
> fix(view):  CHK-1904 add version agnostic base class

- .github/workflows/create_pr_with_version_update.yaml
> [CHK-1249] feat(release): trigger automatic PR on eCommerce projects on commons release

- .github/workflows/create_pr_with_version_update.yaml
> fix(auto-pr): Misc fixes related to Action authorization

- .github/workflows/create_pr_with_version_update.yaml
> refactor(auto-pr): use action to create commit

- .github/workflows/create_pr_with_version_update.yaml
* fix fetch depth when checking out repo
> fix(auto-pr): fix fetch depth when checking out repo

- .github/workflows/create_pr_with_version_update.yaml
> fix(auto-pr): remove env for action

- .github/workflows/create_pr_with_version_update.yaml
> feat: add all eCommerce repos to action

- .github/workflows/create_pr_with_version_update.yaml
Remove workflow dispatch
Remove workflow dispatch
> refactor: remove workflow_dispatch on PR action

- src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/NpgTransactionGatewayAuthorizationData.java
- src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/NpgTransactionGatewayAuthorizationRequestedData.java
- src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/TransactionGatewayAuthorizationRequestedData.java
- src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
- src/test/java/it/pagopa/ecommerce/commons/domain/v2/TransactionTest.java
- src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Move brand from auth completed to auth requested for NPG flow
Move brand from auth completed to auth requested for NPG flow
Junit tests
> feat(NPG): move logo and brand to authorization requested event

- src/main/java/it/pagopa/ecommerce/commons/documents/v2/activation/NpgTransactionGatewayActivationData.java
- src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/NpgTransactionGatewayAuthorizationRequestedData.java
- src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
- src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Add NPG authorization session id. 
This field holds the confirmPayment received `sessionId`. 
This field is optional so it's mapped as optional into event-store too
This sessionId is the one that has to be used in order to perform `getState` NPG API call
Junit tests
> feat: add NPG authorization session id

- clients/api-specs/npg.yaml
- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
- src/test/java/it/pagopa/ecommerce/commons/client/NpgClientPaymentMethodTests.java
- src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Improve npg client refund invocation robustness
Force idempotence key to UUID format
Add optional description for refund request
Fix openapi description
> [CHK-1968] feat(npg): improve refund request parameters type

- src/main/java/it/pagopa/ecommerce/commons/redis/templatewrappers/RedisTemplateWrapper.java
- src/test/java/it/pagopa/ecommerce/commons/redis/v1/templatewrappers/PaymentRequestInfoRedisTemplateWrapperTest.java
- src/test/java/it/pagopa/ecommerce/commons/redis/v2/templatewrappers/PaymentRequestInfoRedisTemplateWrapperTest.java
Added into RedisTeamplateWrapper the method for execute SET with NX. The method used is saveIfAbsent.
**Documentation** : https://redis.io/commands/set/
The change was made to write to redis only if the key does not exist.
> [CHK-2095] feat: added new method saveIfAbsent into RedisTemplateWrapper

- src/main/java/it/pagopa/ecommerce/commons/queues/TracingUtils.java
* set parent correctly when injecting remote span
This PR solves a tracing bug where the parent would not be set correctly when instrumenting traces manually.
Tested with ELK instance in DEV environment
> [CHK-1765] fix(tracing): set parent correctly when injecting remote span

- src/main/java/it/pagopa/ecommerce/commons/exceptions/NpgApiKeyConfigurationException.java
- src/main/java/it/pagopa/ecommerce/commons/utils/NpgPspApiKeysConfig.java
- src/test/java/it/pagopa/ecommerce/commons/utils/NpgPspApiKeysConfigTest.java
Porting of NPG per PSP api key configuration parsing logic.
This logic have been ported from transactions-service in order to make it centralized and available for all eCommerce modules that must use a per PSP api key configuration for call NPG
Junit tests
> feat(npg): [CHK-2113] - PSP api key configuration read porting

- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
- src/main/java/it/pagopa/ecommerce/commons/exceptions/NpgApiKeyMissingPspRequested.java
- src/main/java/it/pagopa/ecommerce/commons/exceptions/NpgApiKeyMissingPspRequestedException.java
- src/main/java/it/pagopa/ecommerce/commons/exceptions/NpgResponseException.java
- src/main/java/it/pagopa/ecommerce/commons/utils/NpgPspApiKeysConfig.java
- src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
- src/test/java/it/pagopa/ecommerce/commons/utils/NpgPspApiKeysConfigTest.java
* add HTTP status code field to `NpgResponseException`
* throw exception when requesting missing API key from NPG API key config
> refactor(npg): misc NPG refactorings

- .github/workflows/create_pr_with_version_update.yaml
* fix committer in automatic PRs when releasing new version
> fix(release): fix committer in automatic PRs when releasing new version

- clients/api-specs/npg.yaml
- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
- src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
* updated NPG API spec to version 0.7
* updated corresponding NPG client and tests
NPG API spec was updated
> [CHK-2123] feat(npg): update NPG spec to v0.7

- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
- src/main/java/it/pagopa/ecommerce/commons/exceptions/UniqueIdGenerationException.java
- src/main/java/it/pagopa/ecommerce/commons/redis/templatewrappers/UniqueIdTemplateWrapper.java
- src/main/java/it/pagopa/ecommerce/commons/repositories/UniqueIdDocument.java
- src/main/java/it/pagopa/ecommerce/commons/utils/UniqueIdUtils.java
- src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
- src/test/java/it/pagopa/ecommerce/commons/utils/UniqueIdUtilsTests.java
Added new method for execute NPG build method with SUBSEQUENT_PAYMENT action and contractId
Added uniqueId id generation method and REDIS document
The change was made to manage payment by wallet
> CHK-2188 feat: added method for execute npg build with subsequent payment

- pom.xml
- src/main/java/it/pagopa/ecommerce/commons/domain/Claims.java
- src/main/java/it/pagopa/ecommerce/commons/exceptions/JWTTokenGenerationException.java
- src/main/java/it/pagopa/ecommerce/commons/utils/JwtTokenUtils.java
- src/test/java/it/pagopa/ecommerce/commons/utils/JwtTokenUtilsTests.java
Added class for generate token with optional claims "paymentMethodId" , "transactionId" , "orderId"
The change was made to check the JWT on the NPG notification policy
Unit tests
> CHK-2231 feat: added logic for generate jwt with optional claims

- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
- src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Add method to build and exchange NPG order/build calls for APM.
This api call differs from other order/build calls for the fact that amount is valued with the transaction total amount
Junit tests
> feat: add transaction amount for order build call

- src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionAuthorizationRequestData.java
- src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/RedirectTransactionGatewayAuthorizationData.java
- src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/RedirectTransactionGatewayAuthorizationRequestedData.java
- src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/TransactionGatewayAuthorizationData.java
- src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/TransactionGatewayAuthorizationRequestedData.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/pojos/BaseTransactionWithCompletedAuthorization.java
- src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
- src/test/java/it/pagopa/ecommerce/commons/domain/v2/TransactionTest.java
- src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Add event for handle transactions performed with redirect payment gateway
Add event for handle transactions performed with redirect payment gateway
Junit tests
> feat(redirect): add events data details for redirect transactions

- src/main/java/it/pagopa/ecommerce/commons/documents/v2/Transaction.java
Add `gatewayAuthorizationStatus` into V2 transaction view as a nullable fields (valued when a transaction authorization PATCH request is receved)
Add `gatewayAuthorizationStatus` into V2 transaction view
> feat: add gateway authorization status into transactions view

- src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/NpgTransactionGatewayAuthorizationData.java
- src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
- src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Add NPG error code into authorization completed data
Add NPG error code into authorization completed data
> feat: add NPG error code into authorization completed data

- src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionAuthorizationRequestData.java
- src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionAuthorizationRequestData.java
Remove postepay gateway enumeration
Remove postepay gateway enumeration
> fix: remove postepay logic

- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
- src/main/java/it/pagopa/ecommerce/commons/exceptions/NpgResponseException.java
- src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Make NPG error responses error codes lenient
This modification is needed since NPG error codes list is not finite and can dynamically be changed
Junit tests
> fix: make NPG error code decoding lenient

- src/main/java/it/pagopa/ecommerce/commons/client/NodeForwarderClient.java
- src/test/java/it/pagopa/ecommerce/commons/client/NodeForwarderClientTest.java
Add log forwarder error response body
Add log forwarder error response body
> Log node forwarder error response

- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionExpired.java
- src/test/java/it/pagopa/ecommerce/commons/domain/v2/TransactionTest.java
Handle send payment result received after transaction expiration in transaction event reduce operation for v2 events
Handle send payment result received after transaction expiration in transaction event reduce operation for v2 events
Junit tests
> feat: handle send payment result after expiration for v2 events

- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
- src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Fix apiKey position in npg client creation
> [CHK-2627] fix position of the api key

- src/main/java/it/pagopa/ecommerce/commons/documents/v2/Transaction.java
- src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionActivatedData.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/EmptyTransaction.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionActivated.java
- src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
- src/test/java/it/pagopa/ecommerce/commons/queues/StrictJsonSerializerProviderTest.java
- src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Add user id into transaction activated event and view.
`userId` is an optional field that will be populated with user unique
> feat: add user id into transaction activated event and view

- src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/NpgTransactionGatewayAuthorizationData.java
- src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
- src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Add `validationServiceId` field for NPG auth completed event data. This field will be received for MyBank transactions and into NPG `POST notification` additionalData api call body
This field, received by NPG into POST notification api call has to be used to populate Node close payment additionalData for MyBank transactions
Junit tests
> feat: add validationServiceId NPG auth completed field

- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
- src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Add tracing for NPG HTTP received error codes into NpgClient* span
This modification is needed to trace NPG received HTTP error codes
Junit test
> feat(monitoring): trace NPG http error codes into error span

- src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/NpgTransactionGatewayAuthorizationRequestedData.java
- src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/WalletInfo.java
- src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
- src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Add wallet info field to NPG authorization requested data.
This optional structure contains wallet info in case of wallet performed transaction
This PR add wallet info tracing into eCommerce events for NPG wallet performed transactions
> feat: add optional details for wallet into NPG auth requested data

- src/main/java/it/pagopa/ecommerce/commons/domain/BIN.java
- src/main/java/it/pagopa/ecommerce/commons/domain/CardLastFourDigits.java
- src/test/java/it/pagopa/ecommerce/commons/domain/BINTest.java
- src/test/java/it/pagopa/ecommerce/commons/domain/CardLastFourDigitsTest.java
* add `BIN` and `CardLastFourDigits` domain classes
This classes model a BIN (Bank Identification Number) and the last four digits of a credit/debit card PAN
This information is used in eCommerce to handle fee computation.
Depends on #191
> feat: add `BIN` and `CardLastFourDigits` domain classes

- src/main/java/it/pagopa/ecommerce/commons/documents/PaymentNotice.java
- src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionUserReceiptData.java
- src/main/java/it/pagopa/ecommerce/commons/domain/CompanyName.java
- src/main/java/it/pagopa/ecommerce/commons/domain/PaymentNotice.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/EmptyTransaction.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionActivated.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/pojos/BaseTransactionWithPaymentToken.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/EmptyTransaction.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionActivated.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/pojos/BaseTransactionWithPaymentToken.java
- src/test/java/it/pagopa/ecommerce/commons/documents/v1/serialization/TransactionEventTypeResolverTest.java
- src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
- src/test/java/it/pagopa/ecommerce/commons/queues/StrictJsonSerializerProviderTest.java
- src/test/java/it/pagopa/ecommerce/commons/v1/TransactionTestUtils.java
- src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
- Add `companyName` into transaction activated data
- Remove `receivingOfficeName` and `paymentDescription` fields from TransactionUserReceiptData
eCommerce will use company name and description received in Nodo activate response to populate, for each payment notice, the corresponding fields to be sent into user email instead of the one's received into sendPaymentResultBody
Junit tests
> feat: add companyName into transaction activated data + removed data from add user receipt

- clients/api-specs/npg.yaml
- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
- src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
This PR update npg openapi spec by adding GET /orders/{ordersId} which allows to retrieve info about order and all associated operations.
- update openapi spec
- update ngp client class
- Unit test
- Tested during local eCommerce deployment by trying to parse responses from NPG mock which returns a real NPG payload
> feat(npg): [CHK-2833] Add GET order npg

- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionWithRefundError.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionWithRefundRequested.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/pojos/BaseTransactionRefunded.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/pojos/BaseTransactionWithRefundRequested.java
- src/test/java/it/pagopa/ecommerce/commons/domain/v2/TransactionTest.java
- src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Handle reduce for authorization gateway data on refund requested events
Handle reduce for authorization gateway data on refund requested events
Junit tests
> feat: handle reduce for new event structure

- clients/api-specs/npg.yaml
- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
- src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Updated API key header management for NPG APIs.
The management of the API keys for the NpgClient exposes potential side effects when concurrent access to the client occurs. With this change, the API key is specified for each API call, rather than once when the client is instantiated.
Unit Test
> [CHK-2262] update api npg client

- src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionRefundErrorData.java
Add constructor to `TransactionRefundErrorData`
Add constructor to `TransactionRefundErrorData`
Junit tests
> fix: add explicit constructor with args

- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
Add NPG `SATISPAY` payment method enumeration
This modification is needed in order to enable satispay as NPG guest payment method
Local project build
> feat(npg): add satispay payment service name

- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
Rename NPG payment method service name from `SATISPAY` to `SATISPAY_DIRECT` 
Rename NPG payment method service name from `SATISPAY` to `SATISPAY_DIRECT`
> feat(NPG client): rename satispay to satispay direct

- src/main/java/it/pagopa/ecommerce/commons/redis/templatewrappers/ExclusiveLockDocumentWrapper.java
- src/main/java/it/pagopa/ecommerce/commons/repositories/ExclusiveLockDocument.java
- src/test/java/it/pagopa/ecommerce/commons/redis/templatewrappers/ExclusiveLockDocumentWrapperTest.java
Add exclusive locking Redis template wrapper: this wrapper can be used to perform the `saveIfAbsent` method call that will return true iff the document is not present making it possible to use this redis template as a distributed locking mechanism
This implementation will be used by transactions-service for reject duplicated PATCH auth-requests received in a two seconds time window
Junit tests + local tests with eCommerce local (using transactions-service PATCH auth-requests duplicate call implementation)
> feat: add exclusive lock template wrapper

- src/main/java/it/pagopa/ecommerce/commons/utils/OpenTelemetryUtils.java
- src/main/java/it/pagopa/ecommerce/commons/utils/UpdateTransactionStatusTracerUtils.java
- src/test/java/it/pagopa/ecommerce/commons/utils/OpenTelemetryUtilsTest.java
- src/test/java/it/pagopa/ecommerce/commons/utils/UpdateTransactionStatusTracerUtilsTest.java
Move UpdateTransactionStatusTracerUtils from transactions-service to commons in order to make this utility class to be used by event dispatcher with the same span attribute names
Move UpdateTransactionStatusTracerUtils from transactions-service to commons in order to make this utility class to be used by event dispatcher with the same span attribute names
Junit tests
> feat: move update transaction status update utils to commons

- src/main/java/it/pagopa/ecommerce/commons/documents/v2/Transaction.java
- src/test/java/it/pagopa/ecommerce/commons/documents/v2/ClientIdTest.java
* add WISP client id for transactions
This PR adds a `WISP` client id used for eCommerce to identify transactions created through the wisp-dismantling mechanism.
> [CHK-3119] feat: add WISP client id for transactions

- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
- src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
- added a new method to the NPG client with provides access to the language selector
- if language is 2bytes (it, en) -> it gets converted to 3bytes (ITA, ENG, etc...)
This change is part of a bigger task aiming to provide NPG with the language preference as set by the user on the checkout FE.
Unit test
> feat: [CHK-3253] now common supports on NPG client language parameter

- src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
- src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
- added missing override for buildFormForPayment
This change is part of a bigger task aiming to provide NPG with the language preference as set by the user on the checkout FE.
Unit test
> Fix: buildForm inner method now is public 

- src/main/java/it/pagopa/ecommerce/commons/utils/NpgClientUtils.java
- Handle paymentCircuit null for NPG call getOrder
If the paymentCircuit is null, the method must return the paymentEndToEndID and not null
JUnit Test
> [PPABV-67] Handle paymentCircuit null for NPG call getOrder

- src/main/java/it/pagopa/ecommerce/commons/utils/NpgClientUtils.java
- src/test/java/it/pagopa/ecommerce/commons/utils/NpgClientUtilsTest.java
- fix to handle  `paymentMethod` for `paymentEndToEndId`
The goal of this PR is to handle  `paymentMethod` for `paymentEndToEndId`, avoiding             `throw new IllegalArgumentException("Invalid payment method service name: '%s'".formatted(serviceName));`.
The issue concerns the management of the `paymentE2EId` during the reading of the GET state response:
`- error.message: Invalid payment method service name: 'MC'`
The error has been occurring since 12/12/2024 (on December 12, fewer than 100 of these errors occurred, on 13/12 about 2000), which coincides with the release of [PPABV-67]    (version of common applied both on scheduler and event-dispatcher). Upon reviewing the code, the following snippet may need to be analyzed:
```
switch …
```
> fix(getPaymentEndToEndId): PPABV-95  fix paymentMethod for paymentEndToEndId

- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
- src/test/java/it/pagopa/ecommerce/commons/client/NodeForwarderClientTest.java
- updated versions for pipeline tasks which generated deprecation warnings on remote build and deploy processes
- removed mock server hardcoded port to prevent potential port conflicts with other services and make the tests more reliable
This update was needed to prevent future execution failures on code review and deploy pipelines
- code review and deploy pipelines completed successfully and without deprecation warnings
> [PIDM-41] chore(azdo-pipeline-tasks): update tasks versions

- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionExpiredNotAuthorized.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionUserCanceled.java
- src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Fix domain objects hierarchy:
- Make `TransactionExpiredNotAuthorized` extends `BaseTransactionWithPaymentToken`
- Make `TransactionUserCanceled` extends `BaseTransactionWithCancellationRequested`
instead of generic `BaseTransaction` to make those aggregate return transaction activation data too
Since both an expired not authorized and an user canceled transaction can came only from an activated transaction the same have been reflected in code.
This allow user code to retrieve transaction activated data also for user canceled and expired activated only transactions too, used to retrieve data such as userId (see helpdesk service)
Local junit tests against all document aggregates
> fix: reduction class hierarchy

- src/main/java/it/pagopa/ecommerce/commons/domain/FiscalCode.java
- src/test/java/it/pagopa/ecommerce/commons/utils/v2/ConfidentialDataManagerTest.java
- src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Add required class to use fiscal code in helpdesk query
Note for reviewers, sonar error caused by weird uncovered line at annotation level
> [CHK-4050] Add required class to use fiscal code in helpdesk query

- pom.xml
- src/main/java/it/pagopa/ecommerce/commons/client/JwtIssuerClient.java
- src/main/java/it/pagopa/ecommerce/commons/exceptions/JwtIssuerClientException.java
- src/test/java/it/pagopa/ecommerce/commons/client/JwtIssuerClientTests.java
Add JWT issuer client
- Add code generation goal to pom
- Publish a general available JWT Issuer client and its well known API to get keys and generate a token
- Add JUnit tests
In order to integrate a JWT Issuer client in some ecommerce microservice, it is available into the commons library, avoiding code duplication
> [CHK-4187]: integrate jwt issuer into commons library

- pom.xml
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/EmptyTransaction.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionActivated.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionAuthorizationCompleted.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionClosed.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionExpired.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionWithCancellationRequested.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionWithClosureError.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionWithRefundError.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionWithRefundRequested.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionWithRequestedAuthorization.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionWithRequestedUserReceipt.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionWithUserReceiptError.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionWithUserReceiptKo.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/EmptyTransaction.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionActivated.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionAuthorizationCompleted.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionClosed.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionExpired.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionWithCancellationRequested.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionWithClosureError.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionWithClosureRequested.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionWithRefundError.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionWithRefundRequested.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionWithRequestedAuthorization.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionWithRequestedUserReceipt.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionWithUserReceiptError.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionWithUserReceiptKo.java
- src/main/java/it/pagopa/ecommerce/commons/domain/v2/pojos/BaseTransactionWithCompletedAuthorization.java
This PR removes the `--enable-preview` flag and refactors the code accordingly
- remove `--enable-preview` flag from pom.xml
- refactor the code that was using a syntax not supported without the flag
Preview features are not stable and they cause unexpected behaviors with different jvm versions.
> fix: [PIDM-469] remove --enable-preview flag from maven and adapt code accordingly

- src/main/java/it/pagopa/ecommerce/commons/redis/templatewrappers/v1/RedisTemplateWrapperBuilder.java
- src/main/java/it/pagopa/ecommerce/commons/redis/templatewrappers/v2/RedisTemplateWrapperBuilder.java
Take in charge code deprecation replacing deprecated code with suggested one
Take in charge code deprecation replacing deprecated code with suggested one
junit test
> fix: code deprecation

- .github/actions/publish-maven-artifacts/action.yml
- .github/workflows/create_pr_with_version_update.yaml
- .github/workflows/publish_artifact_and_create_update_pr.yaml
- .github/workflows/publish_artifacts.yaml
Add step to publish maven artifact on new created releases
Add workflow to be run manually for publish artifact on old versions too
Those modification are needed in order to publish artifacts on github packages
Action run
> feat: add artifact publish on new releases

- .github/workflows/publish_artifacts.yaml
> Add checkout

- .github/workflows/publish_artifact_and_create_update_pr.yaml
change action name
change action name
> chore: action name

- .github/workflows/publish_artifact_and_create_update_pr.yaml
- .github/workflows/publish_artifacts.yaml
> fix: action conditions

- .github/workflows/publish_artifact_and_create_update_pr.yaml
> fix: add checkout step

- pom.xml
revert version bumps triggered by action tests
revert version bumps triggered by action tests
> chore: restore pom version

- src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionAuthorizationRequestData.java
- src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
- src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
> [CHK-4499] chore: add isContextualOnboard TransactionAuthorizationRequestData
